# Generated by Django 2.2.5 on 2020-02-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='status',
            new_name='status11',
        ),
    ]
